### ISSUE TITLE
mbn_babel.yml file in AUD recipe

### ISSUE THREAD

**Issue by desh2608** [beer-asr/beer#75]
The AUD recipe requires a config file named `mbn_babel` for feature extraction, but the `conf` directory does not contain any such file. Am I missing something?

**Comment by iondel** [comment]
It's a old configuration settings which needs to be udpated. If you want to run the baseline AUD then replace "mbn_babel" with MFCC. If you want to use the MBN features in your experiment you can extract them whith [this tool](https://github.com/iondel/multilingual-bottleneck-features)

**Comment by desh2608** [comment]
Thanks!
