### ISSUE TITLE
zrc2019 dataset

### ISSUE THREAD

**Issue by Baileyswu** [beer-asr/beer#81]
Hello, I'm a newer to learn AUD, following your readme documents to run this beer system. But I can't find zrc2019 dataset on Google. Could you provide me a share link of this dataset?

**Comment by iondel** [comment]
Hi, 

the ZRC2019 refers to the [zero resource challenge data](https://zerospeech.com/2019/). But becareful, the zrc2019 wasn't updated for quite some time and the recipe will need to be adapted to to the latest version of the code. If you just want a simple start to AUD with a publicly available database, try to run the recipe with the MBOSHI database.  To do this set  `db=mboshi` in the [run.sh](https://github.com/beer-asr/beer/blob/master/recipes/aud/run.sh) file. The recipe should automatically download and prepare the data for you.

**Comment by Baileyswu** [comment]
Thank you iondel! I've changed `db=mboshi` in `run.sh` as you mentioned. Since I don't have SGE and cluster, I rewrite some shells and fix some bugs in `run.sh` ([watch my commit](https://github.com/beer-asr/beer/compare/master...Baileyswu:aud-mboshi)). Still, I can't find `ali` in [this line](https://github.com/beer-asr/beer/blob/95ab39add55804dad081cfdef11d70065ef964b7/recipes/aud/run.sh#L113). I guess it's about alignment but no idea about the whole context. Could you please offer me an `ali`?

**Comment by iondel** [comment]
The `ali` file is the ground truth phonetic alignments I use to evaluate the AUD task (for the NMI metric for instance).  I've added this file to the data preparation script of the mboshi data (see #82).  Please update your branch and try to run again the preparation script. 

The `au_phone_counts.yml` is computed from the scoring script directly so running the scoring with the `ali` file should be sufficient.

**Comment by iondel** [comment]
> Thank you iondel! I've changed `db=mboshi` in `run.sh` as you mentioned. Since I don't have SGE and cluster, I rewrite some shells and fix some bugs in `run.sh` ([watch my commit](https://github.com/beer-asr/beer/compare/master...Baileyswu:aud-mboshi)).

I've seen that you change the `beer features extract` script to accept a list/or stdin
