### ISSUE TITLE
cli/subcommands/hmm/mkphoneloop has no optional argument --concentration

### ISSUE THREAD

**Issue by syfengcuhk** [beer-asr/beer#95]
Hi developers,

When calling 

> steps/hsubspace_aud.sh 

in training AUD system an optional argument fed to 
`beer hmm mkphoneloop --concentration`
is unrecognized. Please see 

> steps/hsubspace_aud.sh

Can I remove this option? Thank you!

**Comment by lucasondel** [comment]
Hi,

@syfengcuhk This is some dead code, you can remove it safely. Currently, when you use the option `gamma_dirichlet_process` in the main run.sh file (this is the default), the concentration parameter of the Dirichlet Process will be learned automatically so no worry about this. 

@bolajiy Looking at the code, I see that we have fixed the truncation to be `truncation / 2` by default ? Shall we remove the option or keep it in case we want to play with the concentration ?

**Comment by bolajiy** [comment]
As you say, the posterior of the concentration parameter is learned anyway so it probably doesn't make much of a difference. I prefer to have it be an argument to `cli` with the default behavior being the current behavior (`concentration = truncation / 2`). This could be important if e.g. the `dirichlet_process` prior is used

**Comment by lucasondel** [comment]
Yes I agree, let's keep it. I'll make the change and I'll let you review the pull request. 
If there any other place where this parameter might be call ?

**Comment by syfengcuhk** [comment]
Thanks for you both!
